language: node_js
node_js: ["0.11"]

# Install Haxe
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib
    - git clone git://github.com/as3boyan/HIDE
    - haxelib install jQueryExtern

script:
    - haxe HIDE.hxml
    - pushd plugins/boyan/bootstrap/alerts && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/menu && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/new-project-dialog && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/script && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/tab-manager && haxe plugin.hxml && popd
    - pushd plugins/boyan/codemirror/editor && haxe plugin.hxml && popd
    - pushd plugins/boyan/events/hotkey && haxe plugin.hxml && popd
    - pushd plugins/boyan/compilation/client && haxe plugin.hxml && popd
    - pushd plugins/boyan/compilation/output && haxe plugin.hxml && popd
    - pushd plugins/boyan/compilation/server && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/layout && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/script && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/ui && haxe plugin.hxml && popd
    - pushd plugins/boyan/nekotools/server && haxe plugin.hxml && popd
    - pushd plugins/boyan/openfl/tools && haxe plugin.hxml && popd
    - pushd plugins/boyan/window/file-dialog && haxe plugin.hxml && popd
    - pushd plugins/boyan/window/preserve-window-state && haxe plugin.hxml && popd
    - pushd plugins/boyan/samples/helloworld && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/file-tree && haxe plugin.hxml && popd 

notifications:
    email: false