language: node_js
node_js: ["0.11"]

# Install Haxe
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib
    - git clone git://github.com/as3boyan/HIDE
    - haxelib install jQueryExtern

script:
    - haxe HIDE.hxml
    - pushd plugins/boyan/ace/editor && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/script && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/filetree && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/menu && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/tabmanager && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/alerts && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/script && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/ui && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/layout && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/split-pane && haxe plugin.hxml && popd
    - pushd plugins/boyan/samples/helloworld && haxe plugin.hxml && popd

notifications:
    email: false