language: node_js
node_js: ["0.11"]

# Install Haxe
before_script:
  - sudo apt-get update                                # run update before installing anything
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
  - sudo apt-get update                                # pull info from ppa
  - sudo apt-get install haxe -y                       # install haxe (and neko)
  - mkdir ~/haxelib                                    # create a folder for installing haxelib
  - haxelib setup ~/haxelib
  - haxelib install jQueryExtern

script:
  - haxe HIDE.hxml
  - cd plugins
  - cd boyan/bootstrap/alerts
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/bootstrap/file-tree
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/bootstrap/menu
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/bootstrap/new-project-dialog
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/bootstrap/project-options
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/bootstrap/script
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/bootstrap/tab-manager
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/codemirror/editor
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/codemirror/zoom
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/compilation/client
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/compilation/output
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/compilation/server
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/completion/client
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/developer-tools/hide
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/events/hotkey
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/jquery/layout
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/jquery/script
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/jquery/ui
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/jquery/xml2json
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/management/open-project
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/nekotools/server
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/management/project-access
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/project/haxe
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/openfl/tools
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/project/openfl
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/tern/server
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/samples/helloworld
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/webgl/three
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/window/drag-and-drop
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/window/file-dialog
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/window/preserve-window-state
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/window/toggle-fullscreen
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/window/zoom
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/management/run-project
  - haxe plugin.hxml
  - cd ../../../
  - cd boyan/presentation/impress/about
  - haxe plugin.hxml
  - cd ../../../../
  - cd boyan/presentation/reveal/plugin-development-tutorial
  - haxe plugin.hxml
  - cd ../../../../
  - cd boyan/project/hide/plugin
  - haxe plugin.hxml
  - cd ../../../../
  - cd boyan/samples/presentation/impress/sample
  - haxe plugin.hxml
  - cd ../../../../../
  - cd boyan/samples/presentation/reveal/sample
  - haxe plugin.hxml
  - cd ../../../../../

notifications:
    email: false
