language: node_js
node_js: ["0.8"]

# Install Haxe
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib
    - git clone git://github.com/as3boyan/HIDE
    - haxelib install jQueryExtern

script:
    - haxe HIDE.hxml
    - cd plugins/boyan/bootstrap
    - haxe plugin.hxml
    - cd ../../..
    - cd plugins/boyan/filetree
    - haxe plugin.hxml
    - cd ../../..
    - cd plugins/boyan/helloworld
    - haxe plugin.hxml
    - cd ../../..
    - cd plugins/boyan/jquery
    - haxe plugin.hxml
    - cd ../../..
    - cd plugins/boyan/menu
    - haxe plugin.hxml
    - cd ../../..
    - cd plugins/boyan/split-pane
    - haxe plugin.hxml
    - cd ../../..
    - cd plugins/boyan/tabmanager
    - haxe plugin.hxml
    - cd ../../..