language: node_js
node_js: ["0.8"]

# Install Haxe
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib
    - git clone git://github.com/as3boyan/HIDE
    - haxelib install jQueryExtern

script:
    - haxe HIDE.hxml
    - haxe --cwd plugins/boyan/bootstrap plugin.hxml
    - haxe --cwd plugins/boyan/filetree plugin.hxml
    - haxe --cwd plugins/boyan/helloworld plugin.hxml
    - haxe --cwd plugins/boyan/jquery plugin.hxml
    - haxe --cwd plugins/boyan/menu plugin.hxml
    - haxe --cwd plugins/boyan/split-pane plugin.hxml
    - haxe --cwd plugins/boyan/tabmanager plugin.hxml