language: node_js
node_js: ["0.8", "0.10"]

# Install Haxe
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - haxelib setup ~/.haxe/lib
    - git clone git://github.com/as3boyan/HIDE
    - haxelib install jQueryExtern
    - wget https://s3.amazonaws.com/node-webkit/v0.8.0/node-webkit-v0.8.0-linux-x64.tar.gz
    - tar -xvzf node-webkit-v0.8.0-linux-x64.tar.gz

script:
    - haxe HIDE.hxml
    - node-webkit-v0.8.0-linux-x64/nw bin test