language: node_js
node_js: ["0.11"]

# Install Haxe
before_script:
    - sudo apt-get install python-software-properties -y # for the next command
    - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
    - sudo apt-get update                                # pull info from ppa
    - sudo apt-get install haxe -y 
    - haxelib install jQueryExtern

script:
    - haxe HIDE.hxml

    - pushd plugins/boyan/bootstrap/alerts && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/file-tree && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/menu && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/new-project-dialog && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/script && haxe plugin.hxml && popd
    - pushd plugins/boyan/bootstrap/tab-manager && haxe plugin.hxml && popd
    - pushd plugins/boyan/compilation/client && haxe plugin.hxml && popd
    - pushd plugins/boyan/codemirror/editor && haxe plugin.hxml && popd
    - pushd plugins/boyan/compilation/output && haxe plugin.hxml && popd
    - pushd plugins/boyan/developer-tools/hide && haxe plugin.hxml && popd
    - pushd plugins/boyan/events/hotkey && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/layout && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/script && haxe plugin.hxml && popd
    - pushd plugins/boyan/compilation/server && haxe plugin.hxml && popd
    - pushd plugins/boyan/jquery/ui && haxe plugin.hxml && popd
    - pushd plugins/boyan/nekotools/server && haxe plugin.hxml && popd
    - pushd plugins/boyan/openfl/tools && haxe plugin.hxml && popd
    - pushd plugins/boyan/project/haxe && haxe plugin.hxml && popd
    - pushd plugins/boyan/project/openfl && haxe plugin.hxml && popd
    - pushd plugins/boyan/samples/helloworld && haxe plugin.hxml && popd
    - pushd plugins/boyan/webgl/three && haxe plugin.hxml && popd
    - pushd plugins/boyan/tern/server && haxe plugin.hxml && popd
    - pushd plugins/boyan/window/file-dialog && haxe plugin.hxml && popd
    - pushd plugins/boyan/window/preserve-window-state && haxe plugin.hxml && popd
    - pushd plugins/boyan/window/toggle-fullscreen && haxe plugin.hxml && popd
    - pushd plugins/boyan/window/zoom && haxe plugin.hxml && popd
    - pushd plugins/boyan/presentation/impress/about && haxe plugin.hxml && popd
    - pushd plugins/boyan/presentation/reveal/plugin-development-tutorial && haxe plugin.hxml && popd
    - pushd plugins/boyan/project/hide/plugin && haxe plugin.hxml && popd
    - pushd plugins/boyan/samples/presentation/impress/sample && haxe plugin.hxml && popd
    - pushd plugins/boyan/samples/presentation/reveal/sample && haxe plugin.hxml && popd

notifications:
    email: false
